# Public requests ----------------------------------------------
###
GET http://127.0.0.1:8000/public HTTP/1.1

###
POST http://127.0.0.1:8000/public/signup HTTP/1.1
Content-Type: application/json

{
    "name": "rizeta",
    "email": "rizeta@gmail.com",
    "password": "epenalarizeta"
}

###
GET http://127.0.0.1:8000/public/lessons HTTP/1.1

###
POST  http://127.0.0.1:8000/public/getLesson HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzgyNjEyMTcsInVzZXJfaWQiOiI1MmFkOTQ0OC04MmQxLTVlZDktOTg4OC0zNDhkMjIzZjk1NTkifQ.BXPaVHB_mA1jvQyit2nHVjpIIzANNTnEho1v84SfipU
Content-Type: application/json

{
    "id": "08ff98f2-41b7-5638-9990-0cf15b36ba54"
}

###
POST http://127.0.0.1:8000/public/login HTTP/1.1
Content-Type: application/json

{
    "email": "rfq@gmail.com",
    "password": "password"
}

###
POST  http://127.0.0.1:8000/private/getUser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzgyNjEyMTcsInVzZXJfaWQiOiI1MmFkOTQ0OC04MmQxLTVlZDktOTg4OC0zNDhkMjIzZjk1NTkifQ.BXPaVHB_mA1jvQyit2nHVjpIIzANNTnEho1v84SfipU
Content-Type: application/json

{
    "id": "73b5e959-a2ed-5ed7-a817-76784a2785d8"
}

###
GET http://127.0.0.1:8000/private HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzgwMjE1MzMsInVzZXJfaWQiOiJkZDAyNTQwOC1iZDAyLTViMDgtOTdjMi01YzkxNWIxMzQwMzUifQ.1c4xKwSROS62ivHZgniwFcPSB3jAknjVvesn4Dfqwds

###
POST http://127.0.0.1:8000/private/newLesson HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzgyNjEyMTcsInVzZXJfaWQiOiI1MmFkOTQ0OC04MmQxLTVlZDktOTg4OC0zNDhkMjIzZjk1NTkifQ.BXPaVHB_mA1jvQyit2nHVjpIIzANNTnEho1v84SfipU
Content-Type: application/json

{
    "title": "Lesson 2",
    "content": "Conent in lesson 2",
    "subject": "Subiect 3"
}

###
GET http://127.0.0.1:8000/public/delete/08ff98f2-41b7-5638-9990-0cf15b36ba54 HTTP/1.1